# Generated by Django 5.0.2 on 2024-03-08 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newmamapesa', '0007_remove_loan_purpose_alter_loantransaction_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loan',
            table='Loans',
        ),
    ]
