# Generated by Django 5.0.2 on 2024-03-09 09:24

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('newmamapesa', '0008_alter_loan_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Currencies',
            },
        ),
        migrations.RemoveField(
            model_name='savingstransaction',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='savingstransaction',
            name='savings_item',
        ),
        migrations.RemoveField(
            model_name='trustscore',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='user',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='phonenumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='grace_period_end_date',
            new_name='approval_date',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='interest_rate',
            new_name='deduction_rate',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='late_payment_penalty_rate',
            new_name='default_rate',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='disbursed',
            new_name='is_disbursed',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='idnumber',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='loan_limit',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='loan_owed',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='collateral',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='grace_period',
        ),
        migrations.RemoveField(
            model_name='savings',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='savings',
            name='start_date',
        ),
        migrations.AddField(
            model_name='loan',
            name='amount_owed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='loan',
            name='default_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='remaining_days',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='payment_gateway',
            field=models.CharField(default=3, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, default=3, max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_type', models.CharField(choices=[('loan_submission', 'Loan Submission'), ('loan_approval', 'Loan Approval'), ('loan_rejection', 'Loan Rejection'), ('loan_disbursement', 'Loan Disbursement'), ('loan_payment', 'Loan Payment'), ('savings_deposit', 'Savings Deposit'), ('savings_withdrawal', 'Savings Withdrawal')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Communications',
            },
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='currency',
            field=models.ManyToManyField(related_name='payment_methods', to='newmamapesa.currency'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20)),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('loan_owed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('loan_limit', models.DecimalField(decimal_places=2, default=Decimal('8000'), max_digits=10)),
                ('verified_identity', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('LOAN_DISBURSEMENT', 'Loan Disbursement'), ('LOAN-REPAYMENT', 'Loan Repayment'), ('SAVINGS_DEPOSIT', 'Savings Deposit'), ('SUPPLIER_WITHDRAWAL', 'Supplier Withdrawal'), ('LOAN_SERVICE_CHARGE', 'Loan Service Charge')], max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('COMPLETED', 'completed'), ('FAILED', 'failed')], default='pending', max_length=50)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newmamapesa.customer')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='newmamapesa.loan')),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='newmamapesa.paymentmethod')),
                ('savings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='newmamapesa.savings')),
            ],
            options={
                'db_table': 'Payments',
            },
        ),
        migrations.DeleteModel(
            name='LoanTransaction',
        ),
        migrations.DeleteModel(
            name='SavingsTransaction',
        ),
        migrations.DeleteModel(
            name='TrustScore',
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
