# Generated by Django 5.0.3 on 2024-03-09 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newmamapesa', '0009_currency_remove_savingstransaction_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='payment_status',
        ),
    ]
