# Generated by Django 5.0.2 on 2024-03-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newmamapesa', '0010_remove_loan_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='remaining_days',
            field=models.IntegerField(default=90),
        ),
    ]
