# Generated by Django 5.0.2 on 2024-03-12 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newmamapesa', '0011_alter_loan_remaining_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='remaining_days',
        ),
    ]
