# Generated by Django 5.0.2 on 2024-03-12 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newmamapesa', '0012_remove_loan_remaining_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='amount_owed',
        ),
    ]
