# Generated by Django 5.0.2 on 2024-03-13 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newmamapesa', '0013_remove_loan_amount_owed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='total_amount_paid',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='verified_identity',
        ),
    ]
